[package]
name = "rust-kzg-zkcrypto"
version = "0.1.0"
edition = "2021"

[dependencies]
kzg = { path = "../kzg"}
kzg-bench = { path = "../kzg-bench" }
blst = {'git' = 'https://github.com/supranational/blst.git'}
pairing = "0.22.0"
bls12_381 = "0.7.0"
num-bigint = "0.4"
rand = "0.8"
rand_core = "0.6"
subtle = "2.2.1"
rayon = "1.5.1"
num_cpus = "1.15.0"
hex = "0.4.2"

[dependencies.ff]
version = "0.12"
default-features = false

[dev-dependencies]
criterion = "0.5.1"

[features]
parallel = ["kzg/parallel"]

[[bench]]
name = "zero_poly"
harness = false

[[bench]]
name = "poly"
harness = false

[[bench]]
name = "das"
harness = false

[[bench]]
name = "fft"
harness = false

[[bench]]
name = "kzg"
harness = false

[[bench]]
name = "fk20"
harness = false

[[bench]]
name = "recover"
harness = false

[[bench]]
name = "eip_4844"
harness = false

[[bench]]
name = "lincomb"
harness = false
