name: benchmarks
on: [push, pull_request, workflow_dispatch]
env:
  C_KZG_4844_GIT_HASH: '624aa60d01da524827123506975431aa5454c80d'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]
        # Excluding mcl for now due to they have different project layout
        backend: [blst, arkworks, zkcrypto]
        include:
          # Setup exec_once_per_backend flag
          - os: ubuntu-latest
            exec_once_per_backend: true
          # Select backends which support wasm & which support ckzg drop-in
          - backend: blst
            support_ckzg: true
          - backend: arkworks
            support_ckzg: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "${{ matrix.backend }} Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path ${{ matrix.backend }}/Cargo.toml

      - name: "${{ matrix.backend }} Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path ${{ matrix.backend }}/Cargo.toml --features parallel

      - name: "${{ matrix.backend }} Benchmark (c-kzg-4844)"
        if: matrix.exec_once_per_backend && matrix.support_ckzg
        run: |
          bash run-c-kzg-4844-benches.sh ${{ matrix.backend }}

      - name: "${{ matrix.backend }} Benchmark (c-kzg-4844 parallel)"
        if: matrix.exec_once_per_backend && matrix.support_ckzg
        run: |
          bash run-c-kzg-4844-benches.sh --parallel ${{ matrix.backend }}
